language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - rm -rf test/